substitutions:
  name: base-32
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  ap_wifi_password: !secret ap_wifi_password
  ota_pwd: !secret ota_pwd
  api_pwd: !secret api_pwd

packages:
  base: 
    url: https://github.com/dj-fiorex/esphome-base
    files: [ base.yaml ]
    refresh: 1 min

esphome:
  name: $name

esp32:
  board: esp32dev
