---
sensor:
  - platform: wifi_signal
    id: signal_wifi
    name: "$name WiFi Signal"

text_sensor:
  - platform: template
    name: "$name Connected To"
    entity_category: diagnostic
    id: bssid
    icon: mdi:router-wireless

  - platform: wifi_info
    ip_address:
      id: ip_address
      name: "$name IP Address"
    mac_address:
      id: mac
      name: "$name MAC"
    bssid:
      name: "$name BSSID"
      internal: true
      on_value:
        then:
          - lambda: |-
              if (x == "D8:32:14:9F:A1:11")
                id(bssid).publish_state("Sranza Giuseppe");
              else if (x == "50:0F:F5:CB:91:71")
                id(bssid).publish_state("Stanza primo piano");           
              else if (x == "50:0F:F5:CB:91:61")
                id(bssid).publish_state("Salone");
              else if (x == "B4:0F:3B:D8:55:99")
                id(bssid).publish_state("Cucina primo piano");
              else
                id(bssid).publish_state(x);